
; CONSTANTS
ZPVARIABLES       = $0090 ; tests/all.asm @ 3
BALLXPOSITION     = $0090 ; " @ 4
BALLYPOSITION     = $0091 ; " @ 5
BALLFRAMECOUNTER  = $0092 ; " @ 6
BALLDIRECTION     = $0093 ; " @ 7
NEXTBALLDIRECTION = $0094 ; " @ 8

; LABELS
LABEL_01          = $2000 ; tests/test_opcodes.asm @ 12
LABEL_02          = $2011 ; " @ 29
LABEL_03          = $2023 ; " @ 46
LABEL_04          = $203B ; " @ 63
LABEL_05          = $204D ; " @ 80
LABEL_06          = $2061 ; " @ 97
LABEL_07          = $2073 ; " @ 114
LABEL_08          = $2087 ; " @ 131
LABEL_09          = $2099 ; " @ 148
LABEL_10          = $20AC ; " @ 165
LABEL_11          = $20BE ; " @ 182
LABEL_12          = $20D7 ; " @ 199
LABEL_13          = $20EF ; " @ 216
LABEL_14          = $2106 ; " @ 233
LABEL_15          = $2118 ; " @ 250
LABEL_16          = $212F ; " @ 267
BOOT_THIS         = $3000 ; tests/all.asm @ 13
SOME              = $3085 ; " @ 52
STOREHERE         = $308A ; " @ 56
ADDR1             = $30C6 ; " @ 105
ADDR2             = $30C7 ; " @ 106
ADDR3             = $30C8 ; " @ 107
TABLE             = $30CD ; " @ 114
SHAPES            = $324D ; " @ 118
SHAPE1            = $325D ; " @ 124
DATA.CMD          = $400B ; " @ 146
DATA.LEN          = $400C ; " @ 147
DATA.TMP          = $400D ; " @ 148
