name: Production Builds

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  buildUnix:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, macos-13]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4
    - name: make
      run: |
        cd src
        make clean
        make
    # Upload the end-user binary artifact
    - uses: actions/upload-artifact@v4
      with:
        name: atasm-${{ matrix.os }}
        path: src/atasm
        retention-days: 1
  buildWin:
    strategy:
      matrix:
        configuration: [Release]
        platform: [x64]
    runs-on: windows-latest
    env:
      Solution_Path: atasm.sln
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@v1.0.2

      - name: Build solution
        run: |
          msbuild ${{ env.Solution_Path }} -p:Configuration:${{ env.Configuration }}
        env:
          Configuration: ${{ matrix.configuration }}
          Platform: ${{ matrix.platform }}        
      # Upload the end-user binary artifact
      - uses: actions/upload-artifact@v4
        with:
          name: atasm-${{ matrix.os }}.exe
          path: bin/atasm.exe
          retention-days: 1
